//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.13 at 12:32:16 AM MSK 
//


package com.bodrov.spring.tutor.soap.department;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bodrov.spring.tutor.soap.department package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bodrov.spring.tutor.soap.department
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestRequest }
     * 
     */
    public TestRequest createTestRequest() {
        return new TestRequest();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link PingResponse }
     * 
     */
    public PingResponse createPingResponse() {
        return new PingResponse();
    }

    /**
     * Create an instance of {@link CreateDepartmentRequest }
     * 
     */
    public CreateDepartmentRequest createCreateDepartmentRequest() {
        return new CreateDepartmentRequest();
    }

    /**
     * Create an instance of {@link CreateDepartmentResponse }
     * 
     */
    public CreateDepartmentResponse createCreateDepartmentResponse() {
        return new CreateDepartmentResponse();
    }

    /**
     * Create an instance of {@link RemoveDepartmentRequest }
     * 
     */
    public RemoveDepartmentRequest createRemoveDepartmentRequest() {
        return new RemoveDepartmentRequest();
    }

    /**
     * Create an instance of {@link RemoveDepartmentResponse }
     * 
     */
    public RemoveDepartmentResponse createRemoveDepartmentResponse() {
        return new RemoveDepartmentResponse();
    }

    /**
     * Create an instance of {@link GetDepartmentRequest }
     * 
     */
    public GetDepartmentRequest createGetDepartmentRequest() {
        return new GetDepartmentRequest();
    }

    /**
     * Create an instance of {@link GetDepartmentResponse }
     * 
     */
    public GetDepartmentResponse createGetDepartmentResponse() {
        return new GetDepartmentResponse();
    }

    /**
     * Create an instance of {@link DepartmentRecord }
     * 
     */
    public DepartmentRecord createDepartmentRecord() {
        return new DepartmentRecord();
    }

    /**
     * Create an instance of {@link ResultRecord }
     * 
     */
    public ResultRecord createResultRecord() {
        return new ResultRecord();
    }

}
