//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.13 at 12:32:16 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bodrov.com/spring/tutor/soap/department", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bodrov.spring.tutor.soap.department;
